name: Build and deploy Node.js app to Azure Web App - dibbs-demo-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add a step to change to the front-end directory
      - name: Change to front-end directory
        run: cd front-end

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
        working-directory: ./front-end

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./front-end

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: ./front-end

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: front-end/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
        working-directory: ./front-end
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dibbs-demo-site'
          slot-name: 'Production'
          package: front-end
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D615B933250E4E6F91AA277A73AD6188 }}
